<?php

/**
 * Displays the active build information for a JWSA deployment
 *
 * Implements hook_requirements().
 */

function jwsa_build_info_drupal_requirements($phase) {
  $requirements = [];
  $build_number = $date = NULL;

  // Attempt to access the file, in the deployed project path
  $build_file = realpath(DRUPAL_ROOT . '/../../../.active-build');

  // Attempt the access the directory name of the build path
  $build_path = dirname(realpath(DRUPAL_ROOT . '/../..'));

  if (file_exists($build_file)) {
  	$array = explode('/',$build_path);
    $build_name = array_pop($array);
    $build_number = intval(file_get_contents($build_file));
    $timestamp = filemtime($build_file);

    $date = \Drupal::service('date.formatter')->format($timestamp);
  }

  // Not known
  else {
    $build_name = '<em>Unknown</em>';
  }

  $requirements['build_information'] = [
    'title' => t('Build information'),
    'value' => [
      '#markup' => $build_name . ($build_number ? " (#{$build_number})" : NULL)
    ],
    'description' => $date ? 'Deployed on ' . $date : NULL,
    'severity' => REQUIREMENT_INFO
  ];

  return $requirements;
}
